use     Object::Pad v0.820;

class   Management::App::MVC::Controller::Input;

inherit Mojolicious::Controller;
use     Management::App::Boilerplate::Code;
use     Template::Nest;
use     Management::App::MVC::Model::BusinessLogic::EntryFactory;
use     Management::App::MVC::Model::BusinessLogic::TimeRange;
use     DateTime;

field   $time_range_class           =   'Management::App::MVC::Model::BusinessLogic::TimeRange';

field   $valid_yyyymmdd             =   qr/
                                            ^                   # Start of string
                                            \p{Digit}{4}        # Two digits
                                            (\-|\/)             # A dash or slash
                                            \p{Digit}{2}        # Two digits
                                            (\-|\/)             # A dash or slash
                                            \p{Digit}{2}        # Two digits
                                            $                   # End of string
                                        /x;                     # We could make this more advanced. Why not limit digits to possible month and day calendar ranges? 
                                                                # I.e. 01-12 for month, and 01 to 31 for days, etc? 

=utf8

=head1 METHODS

=over

=item entries

Assesses the input, and decides whether confirm_input, save_input or request_input pages should be generated.

Renders a text/html layout based on HTML code generated by a Template::Nest render command.
That in turn is based on a layout data structure,
and which data structure to use,
is decided by looking at the input provided from a form.

If the stage form field is present, and is confirm - the data structure is produced by confirm_input method.
If the stage form field is present, and is save - the data structure is produced by the save_input method.
In all other cases - the data structure is produced by the request_input method.

=back

=cut

method reset_add_entries_fields {
    # Reset fields before processing new values for them begins!
    $self->stash('add_entries')->{errors}                     =   {};
    $self->stash('add_entries')->{valid}                      =   {};
    $self->stash('add_entries')->{'successful_submission'}    =   undef;
    return $self;
}

method entries {

    my  $log                        =   $self->logger->clone( prefix => 'Management::App::MVC::Controller::Input::entries' );
    $log->trace('About to set initial values.');

    # Initial Values:
    my  $valid_input                =   $self->reset_add_entries_fields->get_valid_add_entries_input;

    $log->debug(
        (
            $valid_input?  'Valid input.':
            'Invalid input.'
        ),
        { dumping_value => $valid_input },
    );
    $log->debug('What fields failed validation:', { failing_fields => $self->validation->failed });

    my  $layout_data_structure      =   $valid_input && $valid_input->{'stage'}?    $valid_input->{'stage'} eq 'confirm'?   $self->confirm_input($valid_input):
                                                                                    $valid_input->{'stage'} eq 'save'?      $self->save_input($valid_input):
                                                                                    $self->request_input:
                                        $self->request_input;

    $log->debug('Set layout data structure as follows:', { layout_data_structure => $layout_data_structure }, );

    $log->trace('About to start processing.');

    # Processing:
    my  $layout                     =   Template::Nest->new($self->stash->{layout_settings}->@*)->render($layout_data_structure);

    $log->trace('Created layout using Template Nest, and saved it to variable.');

    # Output:
    $self->render(
        text                        =>  $layout,
    );

    $log->trace('Rendered the layout as text/html.');

}

method get_valid_add_entries_input {
     my  $log                        =   $self->logger->clone( prefix => 'Management::App::MVC::Controller::Input::get_valid_add_entries_input' );

    $log->debug('Values before validation:', {dumping_values => $self->validation->input});   
    my  @fields_to_validate = qw(
        time_logging
        yyyymmdd
        stage
    );
    for my $field (@fields_to_validate) {
        my  $error  =   $self->validation->required($field, 'not_empty')->required($field, 'trim')->size(1,undef)->has_error($field)?   $self->language->localise_html(
                                                                                                                                            'confirm_entries.error.empty_or_zero_length',
                                                                                                                                            $self->language->localise("confirm_entries.$field.descriptive_field_name"),
                                                                                                                                        ):

                        ($field eq 'yyyymmdd')
                        && $self->validation->required($field, 'trim')->size(1,undef)->like($valid_yyyymmdd)->has_error($field)?            $self->language->localise_html(
                                                                                                                                            'confirm_entries.error.invalid_date',
                                                                                                                                        ):

                        ($field eq 'stage')
                        && $self->validation->required($field, 'trim')->in('add','confirm','save')->has_error($field)?                  $self->language->localise_html(
                                                                                                                                            'confirm_entries.error.invalid_stage',
                                                                                                                                        ):
                        undef; # Fallback/default.

        my  $valid  =   $self->validation->topic($field)->is_valid? $self->validation->topic($field)->param:
                        undef;  # Does $self->validation->param($field) already default to undef if not valid!? We should test it at some point to see and learn.
                        
        $self->stash('add_entries')->{errors}->{"$field"}   =   $error
                                                                if $error;

        $self->stash('add_entries')->{valid}->{"$field"}    =   $valid
                                                                if $valid;
                                                                
        $log->debug('Error stashed:', { error => $self->stash('add_entries')->{errors}->{"$field"} }) if $error;
        $log->debug('Valid field stashed:', { valid => $self->stash('add_entries')->{valid}->{"$field"} }) if $valid;

    };        

        $log->debug('Errors stashed:', $self->stash('add_entries')->{errors});
        $log->debug('Valid fields stashed:', $self->stash('add_entries')->{valid});

        
    return  $self->stash('add_entries')->{valid};

}

method request_input {

    return {
        TEMPLATE                    =>  'main.htm',
        SCRIPTS                     =>  q{},
        CONTENT                     =>  {
            TEMPLATE                =>  'generic-content.htm',
            'SPECIFIC CONTENT'      =>  {
                TEMPLATE            =>  'add_entries/content.htm',
                PROMPT              =>  $self->language->localise_html('Please enter some data as input...'),
                YYYYMMDD            =>  DateTime->now->ymd,
                STAGE               =>  'confirm',
                
            },
        },
    };

}

method confirm_input ($valid_input = {}) {

    my  $log                        =   $self->logger->clone( prefix => 'Management::App::MVC::Controller::Input::confirm_input' );

    $log->trace('About to set initial values.');

    # Initial values:
    my  @entries                    =   $self->get_entries_from_entryfactory($valid_input);
    my  @entries_layout             =   ();

    $log->trace('Entries array contains [_1] entries.', scalar @entries);
    $log->trace('Moving on to generate the page layout...');

    for my $entry_object (@entries) {
        push @entries_layout        ,   {
            TEMPLATE                =>  'entries.htm',
            'TIME RANGE'            =>  sprintf('%s-%s', $entry_object->start_time, $entry_object->end_time), # Shouldn't there be some logic for if this spans multiple days?
            'DURATION'              =>  $entry_object->duration,
            'CATEGORIES'            =>  join(', ', $entry_object->categories->@*),
            'DETAILS'               =>  $entry_object->details,
        };
    };

    my  $layout_for_entries            =   {
        TEMPLATE                    =>  'confirm_entries/content.htm',

        'TIME RANGE LABEL'          =>  $self->language->localise('Time Range'),
        'DURATION LABEL'            =>  $self->language->localise('Duration'),
        'CATEGORIES LABEL'          =>  $self->language->localise('Categories'),
        'DETAILS LABEL'             =>  $self->language->localise('Details'),
        'QUESTION'                  =>  $self->language->localise('How do you wish to proceed?'),
        'SAVE LABEL'                =>  $self->language->localise('Save'),
        'DISCARD LABEL'             =>  $self->language->localise('Discard'),
        'DATA'                      =>  $valid_input->{'time_logging'},
        'YYYYMMDD'                  =>  $valid_input->{'yyyymmdd'},
        ENTRIES                     =>  [@entries_layout],
    };
    my  $layout_for_no_entries           =   {
        TEMPLATE                    =>  'confirm_entries/no_content.htm',

        'INTRO'                     =>  $self->language->localise('No Time Logging Entries to confirm.'),
        'ADD ENTRIES LABEL'         =>  $self->language->localise('Add Time Logging Entry'),
    };

    my  $layout_data_structure      =   {
        TEMPLATE                    =>  'main.htm',
        SCRIPTS                     =>  q{},

        CONTENT                     =>  {
            TEMPLATE                =>  'generic-content.htm',

            'SPECIFIC CONTENT'      =>  @entries? $layout_for_entries:
                                        $layout_for_no_entries,
        },
    };

    $log->trace('Generated the following layout structure:', $layout_data_structure);

    return $layout_data_structure;

}

method get_entries_from_entryfactory ($valid_input //= {}) {

    # This should be put in a Factory class, as it is delivering a ConcreteProduct - a list of Entries. 
    # There can then be an iterator pattern too to iterate through or over them. 
    # We should think about that, as the business logic may not need the traditional "next" iterator,
    # as entries are processed according to time range.

    return  $valid_input->{'time_logging'}
            && $valid_input->{'yyyymmdd'}
            && $self->config('time_zone')?  Management::App::MVC::Model::BusinessLogic::EntryFactory
                                            ->new(
                                                logger => $self->logger,
                                            )
                                            ->multiple_entries($valid_input->{'yyyymmdd'}, $valid_input->{'time_logging'}, $self->config('time_zone'),):
            (); # Otherwise empty list.

}

method save_input ($valid_input //= {}) {

    return  $self->request_input unless $valid_input->{'time_logging'} && $valid_input->{'yyyymmdd'};

    my  $log                        =   $self->logger->clone( prefix => 'Management::App::MVC::Controller::Input::save_input' );

    $log->trace('About to set initial values.');

    # Initial values:
    my  @entries                    =   $self->get_entries_from_entryfactory($valid_input);
    my  @entries_layout             =   ();

    $log->trace('Entries array contains [_1] entries.', scalar @entries);

    # This could be put in some kinda iterator place...
    foreach my $entry (@entries) {
        my  $saved_entry_id         =   $self->database->data->entry->save($entry)->last_saved_entry_id // $self->language->localise('error.last_saved_entry_id.invalid'); # I worry about how this will perform if we ever do async, and save stuff in parallel.
        $log->trace('Saved Entry and then looked up the last saved entry ID, and got: [_1]', $saved_entry_id);
    };

    # Code to save put here

    return {
        TEMPLATE                    =>  'main.htm',
        SCRIPTS                     =>  q{},
        CONTENT                     =>  {
            TEMPLATE                =>  'generic-content.htm',
            'SPECIFIC CONTENT'      =>  {
                TEMPLATE            =>  'save_input/content.htm',
            },
        },
    };



}

method days {


    $self->logger->trace('About to set initial values.');

    # Initial Values:
    my  $valid_input                =   $self->get_valid_days_input;

    my  $layout_data_structure      =   $valid_input?   $self->show_days($valid_input):
                                        $self->ask_days;

    $self->logger->trace('Set layout data structure as follows:', { layout_data_structure => $layout_data_structure }, );

    $self->logger->trace('About to start processing.');

    # Processing:
    my  $layout                     =   Template::Nest->new($self->stash->{layout_settings}->@*)->render($layout_data_structure);

    $self->logger->trace('Created layout using Template Nest, and saved it to variable.');

    # Output:
    $self->render(
        text                        =>  $layout,
    );

    $self->logger->trace('Rendered the layout as text/html.');

}

method ask_days {

    my  @option_defaults = (
            TEMPLATE                =>  'ask_days/options.htm',
            VALUE                   =>  q{},
            LABEL                   =>  q{}, # can be overriden.
    );
    my  $blank_option               =   { @option_defaults };
    
    my  $year_options = [
        {
            @option_defaults,
            LABEL                   =>  $self->language->localise_html('Select a Year...'),
        },
        $blank_option,
    ];

    my  $month_options = [
        {
            @option_defaults,
            LABEL                   =>  $self->language->localise_html('Select a Month...'),
        },
        $blank_option,
    ];


    for my $value ($time_range_class->list_of_acceptable_years) {
        push $year_options->@*      ,   {
            @option_defaults,
            VALUE                   =>  $value,
            LABEL                   =>  $value,
        };
    };

    for my $value ($time_range_class->list_of_acceptable_months) {
        push $month_options->@*     ,   {
            @option_defaults,
            VALUE                   =>  $value,
            LABEL                   =>  $self->language->localise_html(('options.abbreviated_month.'.$value)),
        };
    };

    return {
        TEMPLATE                    =>  'main.htm',
        SCRIPTS                     =>  q{},
        CONTENT                     =>  {
            TEMPLATE                =>  'generic-content.htm',
            'SPECIFIC CONTENT'      =>  {
                TEMPLATE            =>  'ask_days/content.htm',
                'START YEAR SELECT' =>  {
                    TEMPLATE        =>  'ask_days/selects.htm',
                    TITLE           =>  $self->language->localise_html('Year Selection for beginning of Time Range.'),
                    NAME            =>  'time_range_start_year',
                    OPTIONS         =>  $year_options,
                },
                'START MONTH SELECT'=>  {
                    TEMPLATE        =>  'ask_days/selects.htm',
                    TITLE           =>  $self->language->localise_html('Month Selection for beginning of Time Range.'),
                    NAME            =>  'time_range_start_month',
                    OPTIONS         =>  $month_options,
                },
                'END YEAR SELECT' =>  {
                    TEMPLATE        =>  'ask_days/selects.htm',
                    TITLE           =>  $self->language->localise_html('Year Selection for end of Time Range.'),
                    NAME            =>  'time_range_end_year',
                    OPTIONS         =>  $year_options,
                },
                'END MONTH SELECT'=>  {
                    TEMPLATE        =>  'ask_days/selects.htm',
                    TITLE           =>  $self->language->localise_html('Month Selection for end of Time Range.'),
                    NAME            =>  'time_range_end_month',
                    OPTIONS         =>  $month_options,
                },
            }, # end specific content
        },
    };

}

method show_days {
    return 'Listing some days';
}

method get_valid_days_input {
    # Conditional initial values:
    return  $self->validation->has_data
            && $self->validation->required('time_range_start_year')->in($time_range_class->list_of_acceptable_years)->is_valid
            && $self->validation->required('time_range_start_month')->in($time_range_class->list_of_acceptable_months)->is_valid
            && $self->validation->required('time_range_end_year')->in($time_range_class->list_of_acceptable_years)->is_valid
            && $self->validation->required('time_range_end_month')->in($time_range_class->list_of_acceptable_months)->is_valid?     $self->validation->output:
            undef;

}

__END__